<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="row">
<small class="copyright col-md-5 col-sm-5 col-xs-12">
    <span>Coppyright © 2014  <strong>eMart</strong>. All Rights Reserved.Powered by <strong>ArrowHitech</strong>.</span>
</small>
<div class="paylogo col-md-5 pull-right col-sm-5 col-xs-12">
 <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_contact')->toHtml();?>
</div>
</div>